### ISSUE TITLE
Multiple controllers not working

### ISSUE THREAD

**Issue by masterlt4** [amatho/mupen64plus-input-gca#7]
Hey, 

first of all, thank you very much for this project. I've been using it for a few weeks now and it has been working perfectly so far. 
Last week however I tried playing Mario Party with a friend and the controller that was plugged into the second port was not working at all. So now my question is whether this is intentional ( as in only one controller port is supported ) or an issue of some sort.

**Comment by amatho** [comment]
That's not intentional, so this seems like a bug. To be honest, I'm not sure if I ever properly tested support for multiple controllers... Unfortunately I don't have my adapter at the moment, so it might take a while for this to be fixed :(

**Comment by amatho** [comment]
This was introduced by a breaking change in m64p (loganmc10/m64p#206) which broke multiple controllers with this plugin. It should be fixed in the [newest release](https://github.com/amatho/mupen64plus-input-gca/releases/latest). The ZIP files with "-m64p-compat" are the ones you want (as long as you're using m64p).
