### ISSUE TITLE
C stick input very inconsistent

### ISSUE THREAD

**Issue by giraffehere** [amatho/mupen64plus-input-gca#9]
Hey, thanks for making this plugin. Works as intended for most part, except for the c-stick, which I was getting very inconsistent inputs on for what direction it was going. The x and y buttons also did not work for the c-stick. Using the latest build of mupen64plus, build Date Aug 9 2021

Going back to main configuration, but thought I'd let you know.

**Comment by GhostlyDark** [comment]
Tested the plugin with command line mupen64plus (64-bit, latest release). I found that the C-Stick is always firing two inputs, such as moving down triggers down and left or down and right, but never down on its own. +1 on the secondary bindings for C-Left and C-Right (X and Y) not working.

In case it helps to debug the issue:
Secondary bindings via command line mupen (Input SDL) only work if e.g. first one is an axis and second one is a button. It will not work if both bindings are buttons.
works: `C Button L = "axis(3-) button(3)"`
no good: `C Button L = "button(3) button(4)"`

**Comment by ryxie** [comment]
In agreement that c-stick inputs are extremely inconsistent for me. Otherwise this plugin is fantastic!

**Comment by amatho** [comment]
Sorry for the delay, this should be fixed in [the newest release](../releases/tag/0.5.1)! The code for the X and Y buttons was simply missing, I probably forgot to add them back when implementing configurable bindings.

I have changed the deadzone of the C-stick to be a square, instead of a circle, which should improve the consistency. The default deadzone has also been increased, so I recommend that you either increase it yourself or delete the configuration file to get the new defaults.

Thanks for reporting this!

**Comment by ryxie** [comment]
This is a massive improvement, seems perfectly consistent now. Thanks so much!
